"""
====================================================================
Banking Management System (BMS)

File        : export_service.py
Description : Report Export Service

Exports reports generated by the reporting subsystem.

Responsibilities
----------------
• Export reports to CSV
• Export report dictionaries
• Create output directories
• Preserve column ordering

Author      : Adel Alawiyat / ChatGPT
Python      : 3.13+
====================================================================
"""

from __future__ import annotations

import csv
from pathlib import Path

from reporting.report_generator import Report


class ExportService:
    """
    Exports reports to external file formats.
    """

    #################################################################
    # Construction
    #################################################################

    def __init__(
        self,
        output_directory: str | Path = "reports",
    ) -> None:

        self._output_directory = Path(output_directory)

        self._output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    #################################################################
    # CSV Export
    #################################################################

    def export_csv(
        self,
        report: Report,
        filename: str,
    ) -> Path:
        """
        Export a report to a CSV file.
        """

        file_path = self._output_directory / filename

        with file_path.open(
            mode="w",
            newline="",
            encoding="utf-8",
        ) as csv_file:

            writer = csv.writer(csv_file)

            writer.writerow(report.columns)

            writer.writerows(report.rows)

        return file_path

    #################################################################
    # Properties
    #################################################################

    @property
    def output_directory(self) -> Path:
        """
        Return the configured output directory.
        """

        return self._output_directory

    #################################################################
    # Representation
    #################################################################

    def __repr__(self) -> str:

        return (
            f"{self.__class__.__name__}"
            f"(output_directory='{self._output_directory}')"
        )

    def __str__(self) -> str:

        return "Report Export Service"